"""empty message

Revision ID: 66d13c08e2c0
Revises: 
Create Date: 2020-10-02 10:25:22.777057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d13c08e2c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_user_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'user_id')
    op.add_column('users', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'events', ['event_id'], ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'event_id')
    op.add_column('events', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('events_user_id_fkey', 'events', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
