"""empty message

Revision ID: 7878986c03ad
Revises: 66d13c08e2c0
Create Date: 2020-10-05 13:21:09.404302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7878986c03ad'
down_revision = '66d13c08e2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_description', sa.String(length=500), nullable=True))
    op.drop_column('events', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('events', 'event_description')
    # ### end Alembic commands ###
