"""empty message

Revision ID: d6aa675cd897
Revises: 7878986c03ad
Create Date: 2020-10-05 13:26:57.027109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6aa675cd897'
down_revision = '7878986c03ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['user_id'])
    op.drop_constraint('users_event_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_event_id_fkey', 'users', 'events', ['event_id'], ['event_id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'user_id')
    # ### end Alembic commands ###
