"""empty message

Revision ID: fb2afb8aec01
Revises: d6aa675cd897
Create Date: 2020-10-05 15:05:55.665126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb2afb8aec01'
down_revision = 'd6aa675cd897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'day',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('events', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('events', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('events', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('events', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('events', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('events', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('events', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('events', 'day',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
